/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'batuyıldız' at '11.04.2016 20:55' with Gradle 2.9
 *
 * @author batuyıldız, @date 11.04.2016 20:55
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
